# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Vu <br> Dao
tagline:          'Random thoughts'
description:      'Aspiring software developer/engineer/code monkey, tennis player, and weightlifter'
baseurl:          /

paginate:         5

github: https://github.com/danielvdao
linkedin: https://linkedin.com/in/danielvudao
twitter: https://twitter.com/danyuldow

