# Site settings
title: Daniel Dao
email: daniel.vu.dao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Currently a student studying Computer Science at The University
 of Texas at Austin. 
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: danyuldow
github_username:  danielvdao

# Build settings
markdown: kramdown
