# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Daniel Vu Dao
tagline:          'Random thoughts'
description:      'Aspiring software developer/engineer/code monkey, tennis player, and weightlifter'
baseurl:          /

paginate:         5

github: https://github.com/danielvdao
linkedin: https://linkedin.com/in/danielvudao
twitter: https://twitter.com/danyuldow

