# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Vu Dao
description: ''
url: http://danielvudao.me/
baseurl:          /

paginate:         5

github: https://github.com/danielvdao
linkedin: https://linkedin.com/in/danielvudao
twitter: https://twitter.com/danyuldow

plugins: [jekyll-paginate]
